### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_count'                                                          

### ISSUE THREAD

**Issue by trypsynth** [accessibleapps/gui_builder#3]
Attempting to use a fields.ListBox in my application. It initializes, but attempting to use any method on it results in the error given in the title.
Full traceback:
```
Traceback (most recent call last):                                                                                      
File "P:\code\python\querier\querier.pyw", line 11, in <module>                                                       
main()                                                                                                              
File "P:\code\python\querier\querier.pyw", line 7, in main                                                            
window.display()                                                                                                    
File "C:\programs\python31\lib\site-packages\gui_builder\forms.py", line 161, in display                              
self._predisplay()                                                                                                  
File "C:\programs\python31\lib\site-packages\gui_builder\forms.py", line 170, in _predisplay                          
self.render()                                                                                                       
File "P:\code\python\querier\gui\main_window.py", line 15, in render                                                  
self.service_list.insert_item(i.name, self.service_list.get_count())                                                
File "C:\programs\python31\lib\site-packages\gui_builder\fields.py", line 485, in get_count                           
return self.widget.get_count()                                                                                      
AttributeError: 'NoneType' object has no attribute 'get_count'                                                          
```

**Comment by ctoth** [comment]
You need a super call in render before doing your work.

**Comment by trypsynth** [comment]
Aha, that fixed it. Thanks a ton. Although, this is one of those cases where I say documentation would actually be quite helpful. Currently we have to read the code if we want to learn anything about this lib other than a few very basic examples, and that's not ideal.

**Comment by ctoth** [comment]
I completely agree! Please help by creating some documentation for this library. I don't really have time, I just put it up here for anyone to use if they found it useful. I built it to make building Accessible Apps easier, not really for general use but it would be great to have some docs.

**Comment by trypsynth** [comment]
@ctoth, after tinkering more, I plan on it. Do you have any preference for format? RST, markdown, html, etc?

**Comment by trypsynth** [comment]
Partially related, this might be better to move to a private discussion/somewhere that's not a GH issue, but while tinkering, I can't find a way to make tabbing between different elements, of all things, possible. Here's the smallest example:
```python
from gui_builder import fields, forms
import wx
import sys

app = wx.App()

class Frame(forms.Frame):
	box = fields.CheckBox(label="Meow.")
	button = fields.Button(label="Exit")
	
	@button.add_callback
	def meow(self):
		sys.exit()

frame = Frame(title="Meow", parent=None)
frame.display()
app.MainLoop()
```
If I can get that sorted, the rest of this seems pretty straight forward, but I really have no idea what I'm doing wrong here

**Comment by ctoth** [comment]
Works if you put the controls on a panel:

```
from gui_builder import fields, forms
import wx
import sys

app = wx.App()

class Panel(forms.Panel):
	box = fields.CheckBox(label="Meow.")
	button = fields.Button(label="Exit")
	
	@button.add_callback
	def meow(self):
		sys.exit()


class Frame(forms.Frame):
	panel = Panel()

frame = Frame(title="Meow", parent=None)
frame.display()
app.MainLoop()
```

**Comment by ctoth** [comment]
Also .rst is what we use for other packages so would be best here :)

**Comment by trypsynth** [comment]
Ah, gotcha. Thanks a ton. And sounds good. Will start on those probably this weekend.
